Allow ignore_last_class w/ External Loss Functions
azavea/raster-vision pull request #1027
Opened 2020-10-10 02:23 UTC by jamesmcclain

## Overview

Allow the last class to be ignored when an external loss function is used.  This is done by passing `'force'` to `ignore_last_class` rather than `True` or `False`.

### Checklist

- [ ] Updated `docs/changelog.rst`
- [x] Added `needs-backport` label if PR is bug fix that applies to previous minor release
- [x] Ran scripts/format_code and committed any changes
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

2020-10-15 13:42 UTC, AdeelH commented
If I am understanding this and #1017 correctly, `ignore_last_class=True` does 2 things:
	1. sets `ignore_idx` in `CrossEntropyLoss()`
	2. modifies the model so that it predicts one class less

In case of an external loss function, (1) does not happen, but one might still want (2), though it is not strictly necessary (because if the loss func is ignoring that index anyway, modifying the model does not really have much effect. An unmodified model would not receive any gradient on the weights that predict that last class anyway).

So, I think if all this is clearly noted in the in the documentation for `ignore_last_class`, `'force'` is not needed and just 'True' will suffice.

2020-10-15 13:54 UTC, jamesmcclain commented
> If I am understanding this and #1017 correctly, `ignore_last_class=True` does 2 things:
> 1. sets `ignore_idx` in `CrossEntropyLoss()`
> 2. modifies the model so that it predicts one class less
> 
> In case of an external loss function, (1) does not happen, but one might still want (2), though it is not strictly necessary (because if the loss func is ignoring that index anyway, modifying the model does not really have much effect. An unmodified model would not receive any gradient on the weights that predict that last class anyway).
> 
> So, I think if all this is clearly noted in the in the documentation for `ignore_last_class`, `'force'` is not needed and just `True` will suffice.

It is true that the last class does not get any attention from the gradient, but that is part of the problem.  It is clear that its existence still has some effect on the model because I noticed the `null` class continuing to be predicted well into training when starting from a pretrained model.

2020-10-16 15:21 UTC, AdeelH commented
Fair enough. I still think the description should be clearer about what the difference between `True` and `'force'` is.

2020-10-16 15:23 UTC, AdeelH requested changes

2020-10-16 15:23 UTC, AdeelH commented on rastervision_pytorch_learner/rastervision/pytorch_learner/learner_config.py
>                  'ignore_last_class is not supported with external_loss_def.')
And maybe this error should tell the user to use `'force'` instead

2020-10-16 16:55 UTC, jamesmcclain commented
@AdeelH I have addressed your comment

2020-10-16 17:28 UTC, AdeelH approved these changes

2020-10-16 18:35 UTC, lewfish approved these changes

2020-10-16 19:14 UTC, merged