Type cast before saving chips
azavea/raster-vision pull request #1032
Opened 2020-10-16 13:17 UTC by AdeelH

## Overview

This is a workaround for a problem encountered in the WB project where the tifs were uint16, but almost all the pixel values were < 256, with the rest few being larger.

### Checklist

- [ ] Updated `docs/changelog.rst`
- [x] Added `needs-backport` label if PR is bug fix that applies to previous minor release
- [x] Ran scripts/format_code and committed any changes
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

2020-10-16 16:35 UTC, lewfish requested changes
Maybe I'm missing something here, but it seems like it would be simpler to just add an option to do this in the `RasterSource`. Then you wouldn't need to handle the option in multiple places and it would work for the other computer vision tasks.

2020-10-19 11:50 UTC, AdeelH commented
You mean add it to `RasterSourceConfig` and modify `RasterioSource` and `MultiRasterSource` to handle this conversion?

2020-10-19 16:48 UTC, lewfish commented
> You mean add it to `RasterSourceConfig` and modify `RasterioSource` and `MultiRasterSource` to handle this conversion?

Yes, but hopefully you would only need to modify the `RasterSourceConfig` and `RasterSource` base classes so the `get_chip` method would do the type conversion. I think that work and be simpler, but maybe there's some nuance I'm missing.

2020-10-20 13:09 UTC, jamesmcclain commented
I am late to the party, but there is now a [CastTransformer](https://github.com/azavea/noaa-flood-mapping/blob/master/pipeline/usfimr_raster_pipeline.py#L56) that you can use to cast to any type

2020-10-20 13:56 UTC, AdeelH commented
Closing this because this use case is already covered by `StatsAnalyzer` and `StatsTransformer`, so this PR is not needed.

2020-10-20 13:56 UTC, closed without merging