Fix bug in loading regression data
azavea/raster-vision pull request #1056
Opened 2020-12-16 00:07 UTC by lewfish

## Overview

This PR fixes a small bug in how regression data is loaded that surfaced after the nochip PR was merged. 

## Testing Instructions

* Tested with a pipeline in an external repo that uses the `RegressionLearner`.

2020-12-16 07:39 UTC, AdeelH requested changes

2020-12-16 07:39 UTC, AdeelH commented on rastervision_pytorch_learner/rastervision/pytorch_learner/dataset/dataset.py
>              self.normalize = False
To keep it consistent with object detection, I would just add the check here and set `self.to_pytorch = False` and then modify `regression_transformer()` in `transform.py` to return `x` and `y` in the correct form.

On second thought, perhaps the `y = torch.from_numpy(y).long()` in `__getitem__` is perhaps too strong an assumption. Maybe it should just be `y = torch.from_numpy(y)` and we should expect the transform functions to supply a `y` with the correct data type.

2020-12-27 23:22 UTC, lewfish commented
I added a commit which tries to follow your second suggestion.

2020-12-28 05:16 UTC, AdeelH approved these changes

2020-12-28 15:34 UTC, merged