Documentation updated to indicate backward compatibility of bundles.
azavea/raster-vision pull request #1341
Opened 2022-02-12 18:45 UTC by theoway

## Overview

This PR updates the documentation by adding a note about about the backwards compatibility issues with _Model Zoo_. The note is introduced here in this [section](https://docs.rastervision.io/en/0.13/examples.html#model-zoo), where the user can know about this.

### Checklist

- [x] Added `needs-backport` label if PR is bug fix that applies to previous minor release
- [x] Ran scripts/format_code and committed any changes
- [x] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

## Notes
I don't know if `needs-backport` label is required for documentation change.

## Testing Instructions

* _Documentation change_

Closes #1338

2022-02-14 21:56 UTC, lewfish approved these changes

2022-02-15 08:18 UTC, AdeelH requested changes

2022-02-17 07:01 UTC, theoway commented on docs/examples.rst
> +Note that model bundles are only backward compatible down to version ``0.12``.
@AdeelH Made the suggested edit.

2022-02-17 08:06 UTC, AdeelH approved these changes

2022-02-17 08:48 UTC, merged