Add support for fetching and saving external model definitions
azavea/raster-vision pull request #985
Opened 2020-09-02 14:34 UTC by AdeelH

## Overview

Adds support for fetching (#975) and saving (#974) external model definitions. Currently, only supported for chip classification and semantic segmentation.

- External model definitions can be specified by supplying an `ExternalModuleConfig` to `ModelConfig.external_def`.
- Example usage:
	- classification
	```python3
	model = ClassificationModelConfig(
		external_def=ExternalModuleConfig(
			github_repo='lukemelas/EfficientNet-PyTorch',
			# uri='s3://raster-vision-ahassan/models/EfficientNet-PyTorch.zip',
			name='efficient_net',
			force_reload=False,
			entrypoint='efficientnet_b0',
			entrypoint_kwargs={
				'num_classes': len(class_config.names),
				'pretrained': 'imagenet'
	}))
	```
	- semantic segmentation
	```python3
    model = SemanticSegmentationModelConfig(
		external_def=ExternalModuleConfig(
			github_repo='pytorch/vision',
			name='fcn',
			force_reload=False,
			entrypoint='fcn_resnet50',
			entrypoint_kwargs={
				'num_classes': len(class_config.names),
				'pretrained': False
	}))
	```
- The `learner` uses this config to fetch the code via torch.hub.
- The definition is stored under `<output_uri>/train/modules`.
- During the bundling step, `<output_uri>/train/modules` is copied to the bundle directory and thereby included in the bundle zip file.
- When loading from a bundle, the definition is recovered and its path provided to `learner.__init__` via a new `model_def_path` param.
- The `torch.hub` wrappers can be found at `.../pytorch_learner/utils/torch_hub.py`
- `.../pytorch_learner/utils.py` has been moved to `.../pytorch_learner/utils/utils.py`

### Checklist

- [ ] Updated `docs/changelog.rst`
- [x] Added `needs-backport` label if PR is bug fix that applies to previous minor release
- [x] Ran scripts/format_code and committed any changes
- [ ] Documentation updated if needed
- [x] PR has a name that won't get you publicly shamed for vagueness

## Testing Instructions

- How to test this PR
    - Use examples above. Try with different options.

Closes #974
Closes #975

2020-09-03 09:06 UTC, AdeelH commented
This does not solve #974 directly, but it should now be possible to decouple internal model definition code from the learners and move it all to a separate place, like a new `pytorch_modules` plugin, or a new repo, and use this mechanism to load them.

2020-09-09 15:34 UTC, lewfish requested changes
Looks good overall.

2020-09-10 07:35 UTC, AdeelH commented on rastervision_pytorch_backend/rastervision/pytorch_backend/examples/chip_classification/spacenet_rio_external_model.py
> +    model = ClassificationModelConfig(
Done. Added an `external_model` flag to `get_config()`.

```python3
    if external_model:
        model = ClassificationModelConfig(
            external_def=ExternalModuleConfig(
                github_repo='lukemelas/EfficientNet-PyTorch',
                ...
                }))
    else:
        model = ClassificationModelConfig(backbone=Backbone.resnet50)
```

2020-09-10 07:36 UTC, AdeelH commented on rastervision_pytorch_backend/rastervision/pytorch_backend/pytorch_learner_backend_config.py
> +        if v.external_def is not None:
I have changed it so that the object detection backend checks if `ModelConfig.external_def` has been set and raises an error if it has.

2020-09-10 16:22 UTC, lewfish approved these changes

2020-09-10 17:23 UTC, merged

2020-09-10 17:27 UTC, jamesmcclain commented
:tada: